services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=8080
    networks:
      - jenkins_network
    restart: unless-stopped
networks:
  jenkins_network:
    driver: bridge
