services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    network_mode: host # <- usa a rede do host
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: --httpPort=8080
    restart: unless-stopped
