apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: web
  labels:
    app: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
  selector:
    app: web
